Modified the script to start the Vivado hardware manager
- Added a description so that others know what it does, since unless
  you're a Vivado nut, you won't have a clue what it's purpose is
- Finds the accompanying .tcl script by looking in the location where
  the script is at instead of requiring me to `cd` to the scripts
  directory.

diff --git a/start_hw_server b/start_hw_server
--- a/start_hw_server
+++ b/start_hw_server
@@ -1,5 +1,28 @@
 #!/bin/bash
 
+# Starts the Vivado hardware manager in daemon mode as a background process, if
+# one isn't already running. This allows the hardware manager of other Vivado
+# instances on the network to connect remotely to boards that are physically
+# connected to another machine (e.g., one in a laboratory).
+#
+# As an example, consider the case of an FPGA development board connected via a
+# USB to JTAG programming pod on a lab machine named Alice.  Now imagine that
+# a remote development machine run by Bob wants to program the FPGA.  Alice
+# would run the `start_hw_server` script, wait a couple of seconds, and then
+# identify the IP address, hostname, and available ports that the hardware
+# manager is now running on her machine.  She could use `pgrep` to identify the
+# process, and then use something like `netstat` or `ss` to determine which
+# ports are in use.  Bob would then open the hardware manager from his machine,
+# add Alice's host to the list of targets to look for, and the Digilent board
+# should appear as if it were connected locally to his machine.
+#
+# This script allows one to remotely start the hardware manager on Alice's
+# machine, immediately identify when it's run whether there is already an
+# instance of `hw_server` running, and ultimately, what IP address and ports it
+# is available on.  So, all that is needed on Alice's machine, assuming the
+# firewall is appropriately configured, is SSH access, the Xilinx tools, and the
+# cable drivers installed (common oversight).
+
 # shellcheck disable=SC2181
 
 err() {
@@ -57,12 +80,20 @@ if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
     return 1
 fi
 
+# Make sure that the script we're going to fire up Vivado with exists
+# Hardware server startup script to call Vivado with
+script_name="$(realpath "${0}")"
+scripts_dir="$(dirname "${script_name}")"
+hw_server_tcl="${scripts_dir}/start_hw_server.tcl"
+
+if [[ ! -f "${hw_server_tcl}" ]]; then
+    err "Could not find 'start_hw_server.tcl'. Cannot start hardware server."
+    exit 1
+fi
+
 # Specify which Vivado version we are using
 vivado_version=2024.1
 vivado_root="${TOOLS_ROOT}/Xilinx/Vivado/${vivado_version}"
-
-# Hardware server startup script to call Vivado with
-hw_server_tcl='start_hw_server.tcl'
 
 # Check if an existing Vivado hardware daemon is already running
 hw_server_pid="$(get_hw_server_pid)"
@@ -76,12 +107,6 @@ fi
 # Import Xilinx settings to allow us to start Vivado
 if ! source "${vivado_root}/settings64.sh" >/dev/null 2>&1; then
     err "Could not source ${vivado_root}/settings64.sh. Check TOOLS_ROOT."
-    exit 1
-fi
-
-# Make sure that the script we're going to fire up Vivado with exists
-if [[ ! -f "${hw_server_tcl}" ]]; then
-    err "Could not find ${hw_server_tcl} script. Cannot start harware server."
     exit 1
 fi
 
